# -*- coding: utf-8 -*-
"""Repositorios GitHub

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13MjZnIGkk5o9xVQXXBzzcvipBe6mOMOy

## Importamos los Modulos necesarios
"""

import requests
from bs4 import BeautifulSoup
import math

"""## Ingresamos el Username"""

username = input("Ingresa el Username : ")

"""## Obtenemos la cantidad de Repositorios del usuario"""

repos_per_page = 30
url = f"https://github.com/{username}?tab=repositories"
page = requests.get(url)
soup = BeautifulSoup(page.content, "html.parser")
a_tag = soup.find('a', attrs= {"data-tab-item" : "repositories"})
total_repos = a_tag.span.string 
print(f"El usuario {username} tiene {total_repos} repositorios")

"""## Obtenemos la cantidad de paginas"""

num_pages = math.ceil(int(total_repos) / repos_per_page) 
print(f"Tiene {num_pages} página(s)")

"""## Obtenemos la lista de Repositorios del usuario"""

print(f"{username} --> {total_repos} repositorios")
item = 1

for i in range(1,num_pages+1):
    path = "https://github.com"
    url2 = f"https://github.com/{username}?page={i}&tab=repositories"
    page2 = requests.get(url2)
    soup2 = BeautifulSoup(page2.content, "html.parser")
    links = soup2.find_all("a", attrs={"itemprop":"name codeRepository"})
    for link in links:
      path2 = link.get('href')
      print(f"{item}.- {path}{path2}")
      item +=1